---
abstract: 'XML processing with a clean interface'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Encode: 0
  IO::File: 0
  Module::Build: 0
  Params::Classify: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.008
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Easy
provides:
  XML::Easy:
    file: lib/XML/Easy.pm
    version: 0.008
  XML::Easy::Classify:
    file: lib/XML/Easy/Classify.pm
    version: 0.008
  XML::Easy::Content:
    file: lib/XML/Easy/Content.pm
    version: 0.008
  XML::Easy::Element:
    file: lib/XML/Easy/Element.pm
    version: 0.008
  XML::Easy::NodeBasics:
    file: lib/XML/Easy/NodeBasics.pm
    version: 0.008
  XML::Easy::Syntax:
    file: lib/XML/Easy/Syntax.pm
    version: 0.008
  XML::Easy::Text:
    file: lib/XML/Easy/Text.pm
    version: 0.008
recommends:
  Internals: 0
  XSLoader: 0
requires:
  Exporter: 0
  Params::Classify: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.008
